### ISSUE TITLE
Scrumbling English texts

### ISSUE THREAD

**Issue by Lionslayer** [silnrsi/font-padauk#1]
English texts in Padauk font scramble into single character width in Chrome browser and Firefox browser (disabled by default as the issue here http://scripts.sil.org/cms/scripts/page.php?site_id=projects&item_id=graphite_firefox ).

Chrome screenshot (my.wikipedia.org):
https://postimg.org/image/6s5c8qqzp
https://postimg.org/image/6tfa25sth

Firefox 47 and 48.0.2 by same machine:
https://postimg.org/image/sj5lnsj03/

It also happens in Firefox versions of Windows and Androids.

Note: Scrumbling English texts are small letters. I am writing in capital letters to work around the issue.

**Comment by mhosken** [comment]
This is due to a bug in the fonts in that lowercase letters were labelled as marks to the OpenType. A hangover from the tussle of trying to get OpenType to do what we want. A fix is already committed but not yet released.

**Comment by tim-eves** [comment]
This bug is now fixed in the released version 3.001 available on the official product page for Padauk http://software.sil.org/padauk/download/
