### ISSUE TITLE
Change Sgaw Karen defaults

### ISSUE THREAD

**Issue by mhosken** [silnrsi/font-padauk#11]
After some polling of Sgaw Karen users, there is a general expression that they would prefer a vertical hato and round washwe. But they still want the left ldot.

**Comment by jvgaultney** [comment]
Is this a design issue or a language-specific defaults issue? What has to change - the glyphs, the glyph names, or some other control file?

**Comment by mhosken** [comment]
This is smart code changes only. Change the default features for when Sgaw Karen is selected. No font design needed.

**Comment by jcoblentz** [comment]
Graphite and OpenType code modified for this issue.
