### ISSUE TITLE
Padauk bytecode fails with FreeType 2.7.1

### ISSUE THREAD

**Issue by lemzwerg** [silnrsi/font-padauk#12]
Please produce a new release using the last version of ttfautohint!  The currently released fonts fail with FreeType 2.7.1, partly because of buggy bytecode (due to a bug in ttfautohint, which I've meanwhile fixed), partly due to the new bytecode loop constraints in FreeType which are a bit too strict.

Note that the ttfautohint version you were using apparently didn't contain support for Myanmar at all – the current version, 1.6, *does* have support, and it also doesn't trigger the problem with FreeType.

**Comment by n7s** [comment]
Our build toolchain now has version 1.6 (the package was backported to xenial) and the build server should pick it up soon so we can test the fix.  Thanks!

**Comment by n7s** [comment]
Actually, there is a dependency issue with the 1.6 backported package. Might take a little longer.

**Comment by n7s** [comment]
The backported package has now been built properly.

**Comment by jcoblentz** [comment]
Maintenance version 3.003 was built using ttfautohint v 1.6.
