### ISSUE TITLE
1037 shaping

### ISSUE THREAD

**Issue by mhosken** [silnrsi/font-padauk#16]
Some issues for Eastern Pwo Karen

* ကၠ့ should have the lower dot to the right also \u107E\u1037 and \u106F\u1037 should also have the lower dot move right not left.
* Opentype \u106F\u102F results in a strange ordering with the 102F to the right of the under stick. Want tall form as per Graphite. Also with \u107E

**Comment by jcoblentz** [comment]
Added u106F and u1070 to @needsUtall so the tall form is rendered. (fixes issue 16 part B) Cleaned up the lookup.

To fix the 1037 issue, u1060 should have an attachment point of LM. Also u106F, u1070 and u107E should have the position of the L attachment point corrected.
