### ISSUE TITLE
Double character with Padauk

### ISSUE THREAD

**Issue by stephenspurlock** [silnrsi/font-padauk#17]
I am on a Mac computer running 10.13.3 with Padauk 3.003 installed. I have tried the Myanmar - QWERTY input method included with macOS and the [keymagic](http://keymagic.net) input method on the Myanmar3std input.

My issue: I get a double "did cho ngin" "ု" when paired with “thay thay tin"  "  ံ". For example: တုံ. That works in my web browser but in Pages with the Padauk font there are two "  ုု". If I change the font to Myanmar Sangam MN or Myanmar 3 it works, but not with Padauk. I like the Padauk typeface and thank you for your work with it. 

I might not understand the input method because Burmese is my second language but it seems to have a bug. I hope this is helpful.

![padauk issue](https://user-images.githubusercontent.com/36468977/36191783-6a1d02ee-1191-11e8-9b82-b42637e68ca4.jpg)

[Padauk Issue.pdf](https://github.com/silnrsi/font-padauk/files/1722978/Padauk.Issue.pdf)

**Comment by mhosken** [comment]
I think this is fixed or else can't reproduce now.
