### ISSUE TITLE
Double Character Rendering in OSX

### ISSUE THREAD

**Issue by Lionslayer** [silnrsi/font-padauk#2]
u1031 and u103C render twice for a single character in OSX Safari and Office suite (Pages, Numbers, Keynote). It doesn't happen in iOS Safari browser.

Example texts are from Myanmar WIkipedia page my.wikipedia.org and Padauk Test suite (my).
https://postimg.org/image/h0xtekf1h
https://postimg.org/image/gf8uigjz9

**Comment by mhosken** [comment]
It's hard to get a consistent OpenType engine that misbehaves in the same way as all the rest. It looks like these Mac OpenType engines are not behaving themselves. I would pass this as a bug to Apple and see whether it has been fixed already (since iOS seems to be working OK).
