### ISSUE TITLE
Errors reported by FontValidator

### ISSUE THREAD

**Issue by jcoblentz** [silnrsi/font-padauk#23]
FontValidator reports hundreds of misoriented contour, some duplicated knots, intersecting contours and incorrect bounding box errors which need to be investigated.

**Comment by n7s** [comment]
The countour-related issues could also be flagged/investigated via this Glyphs script: https://github.com/mekkablue/Glyphs-Scripts/blob/master/Test/Preflight%20Font.py   (Script -> mekkablue-scripts -> Test -> Preflight Font)
