### ISSUE TITLE
Mon Thai variant glyphs

### ISSUE THREAD

**Issue by mhosken** [silnrsi/font-padauk#27]
The Mon in Thailand have a significantly different style to Mon in Burma. The enclosed font shows the variant style. The proposal is to add .thai variants for the following glyphs: u1003, u100B, u100C, u100D, u100E, u1012, u1014, u101E, u1020, u1021, u1023, u103F, u1049, u104A, u104B. In addition the kinzi is a different style. N.B. in Mon kinzi is spelled 105A 103A 1039.
[Mon3_old.zip](https://github.com/silnrsi/font-padauk/files/3484601/Mon3_old.zip)

**Comment by jvgaultney** [comment]
So the suffix for the new variants (including the kinzi) should be .thai - correct?

**Comment by mhosken** [comment]
yes. .thai

**Comment by jvgaultney** [comment]
The glyphs (u1003.thai, etc.) have been added. The kinzi is temporarily called 'kinzi' - you'll need to change that to whatever name is most appropriate. I only adjusted APs when the adjustment seemed obvious, but I don't know anything about the AP scheme. So someone else will need to determine what APs are needed for each glyph, test, and adjust.

**Comment by jcoblentz** [comment]
**Subjoined glyphs to complement the normal Mon Thai variants.** 
Glyphs needed: Medium sized glyphs (similar size as the .med glyphs) for the following Mon Thai glyphs:
u1003.thai, u100B.thai, u100C.thai, u100D.thai, u100E.thai, u1012.thai, u1014.thai, u101E.thai and u1020.thai. They are needed for each of the faces.
Encoding: All are unencoded.
Attachment points: Should be similar to their corresponding regular .med glyphs.

**Comment by jvgaultney** [comment]
How should these be named?

**Comment by jcoblentz** [comment]
Becca will be working on this.
[Padauk issue 27 – Mon Thai (subjoined) variants.pdf](https://github.com/silnrsi/font-padauk/files/5035862/Padauk.issue.27.Mon.Thai.subjoined.variants.pdf)

**Comment by Anontamon** [comment]
Notes on alternate letterforms in Mon thai languages
http://www.unicode.org/L2/L2020/20163-arakanese-mon.pdf

**Comment by jcoblentz** [comment]
@Anontamon Thank you. This is helpful.
