### ISSUE TITLE
collision of u101B and u103B in Bold fonts

### ISSUE THREAD

**Issue by jcoblentz** [silnrsi/font-padauk#28]
Collision of u101B and u103B in Bold and Book-Bold. It's a character sequence found in Pa'o Karen (blk)

![Padauk collision u101B u103B](https://user-images.githubusercontent.com/12460265/63907579-3c674d80-c9d9-11e9-82d4-cc75796d4187.jpg)

**Comment by mhosken** [comment]
OpenType or Graphite?

**Comment by jcoblentz** [comment]
It's the default position of both characters but I don't think adjusting it
in the .ufo is feasible.  Smart code positioning to adjust the pair will
involve both OpenType and Graphite. It appears some adjustment is also
necessary for the pair in Book (Regular).

**Comment by jcoblentz** [comment]
Ligatures created. OT and Graphite support added.
