### ISSUE TITLE
Sgaw shaping problems

### ISSUE THREAD

**Issue by mhosken** [silnrsi/font-padauk#29]
There are various styles of sgaw that people like. We need to support more than just the default, and even do that right!
![image](https://user-images.githubusercontent.com/5687149/78626971-804cfa00-78ba-11ea-80fa-0098beabe8a7.png)

Some sub-issues to address:
- Need to add OT features for the various controls in the graphite: hsln, wtri
- Do we decompose U+1061 and U+1066 to slant the subjoined ha component?
- Need to fix the U+1066 U+1037 positioning

**Comment by jcoblentz** [comment]
This was fixed is https://github.com/silnrsi/font-padauk/commit/7708bf1456e6991b65ba36513760d50e4c8def9d and https://github.com/silnrsi/font-padauk/commit/91885d8e71fdd6e473bc10430a68ad20aab0d6d3
