### ISSUE TITLE
khamti diacritic positioning

### ISSUE THREAD

**Issue by mhosken** [silnrsi/font-padauk#33]
A couple of diacritic base positionings to fix.
![image](https://user-images.githubusercontent.com/5687149/86076668-ac8ca700-bab4-11ea-8206-eb6ee5497bf9.png)
and 
![image](https://user-images.githubusercontent.com/5687149/86076739-ce862980-bab4-11ea-8a30-5f1a5c480291.png)

**Comment by jcoblentz** [comment]
Does this look like the correct positioning?

![image](https://user-images.githubusercontent.com/12460265/112223674-dca24a00-8bef-11eb-8cde-6cf16e461fb8.png)

**Comment by jcoblentz** [comment]
Screenshot of new positioning. An average was used to calculate the positioning since the diacritics differ a bit in width.

![image](https://user-images.githubusercontent.com/12460265/112901477-0d77f880-90a2-11eb-86d0-7bd6f12d78c7.png)
