### ISSUE TITLE
quotedblbase has comma component duplicated at same location

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/font-padauk#34]
Found by fontbakery in both regular and bold. Here is what the UFOs have:

```
  <outline>
    <component base="comma"/>
    <component base="comma"/>
  </outline>

```

**Comment by jcoblentz** [comment]
This was fixed in https://github.com/silnrsi/font-padauk/commit/81d348e4be7e0fe0f7415a60cfb7b345fcf15306
