### ISSUE TITLE
Conjunct ္တွ does not combine well with pre-vowel (E or SHAN E)

### ISSUE THREAD

**Issue by uoa-xguo270** [silnrsi/font-padauk#36]
The sequence ္တွ (VIRAMA, TA, MEDIAL WA) causes a vowel that would normally be displayed **before** the base consonant (E or SHAN E) to display **after** the consonant. It is unknown if other medial sequences also cause this problem.
![image](https://user-images.githubusercontent.com/68937723/110187239-835eba80-7e7c-11eb-9adf-347723e63d84.png)

**Comment by jcoblentz** [comment]
Thank you for reporting this bug. NB: This is a Graphite bug. OpenType looks good.
