### ISSUE TITLE
Tall AA + AI inconsistency 

### ISSUE THREAD

**Issue by guocuozuoduo** [silnrsi/font-padauk#37]
Mon uses the vowel sign AI (-ဲ) as a short hand for YA + ASAT (-ယ်). Therefore, combinations like KA + AA + AI ကာဲ can occur. However, if the form for the AA vowel is the Tall AA (-ါ) as required by some consonants, then combinations like GA + Tall AA + AI ဂါဲ will display problematically. The only workaround is to switch the ordering of input, e.g. GA + AI + Tall AA ဂဲါ, making the ordering inconsistent with the usual ordering of AA + AI (with KA it will be ကာဲ). This is also unsatisfactory as the kerning between GA and Tall AA is inconsistent with the same combination without Tall AA ဂါ.
![image](https://user-images.githubusercontent.com/32423716/116540186-eda45080-a93d-11eb-8144-da6b3b17a002.png)
- Black: KA and GA combined with AA and Tall AA respectively without AI.
- Red: KA + AI + AA: not used in Mon, included here only for completeness.
- Green: KA + AA + AI: the correct form used in Mon.
- Blue: the workaround solution GA + AI + Tall AA, with unsatisfactory kerning and inconsistent ordering of input.
- Yellow: the preferred input GA + Tall AA + AI which displays incorrectly.

The following screenshot is from [a video in Mon](https://www.youtube.com/watch?v=X9WfB3ERTTI) that shows the expected appearance:
![image](https://user-images.githubusercontent.com/32423716/116540924-e762a400-a93e-11eb-86db-41e7ed693395.png)
Note also the special placement of the vowel sign I when combined with AI, but that is not the subject of this issue.

**Comment by jcoblentz** [comment]
Thank you for your very good detailed explanation of the issue.

**Comment by jcoblentz** [comment]
We will need to do some analysis to see if adding an upper AP (U or Y) to u102B would be appropriate.  If not, create a ligature u102B_u1032 and a Character Variant feature to use in LibreOffice and web browsers - also a Stylistic Set feature (if we can spare one) to use in MS Word and Adobe InDesign.

**Comment by jcoblentz** [comment]
Used a special "AA" as the attachment point to keep interactions with other base characters with "U" or "Y" to  minimum.  

![image](https://user-images.githubusercontent.com/12460265/116950785-5bed5980-ac43-11eb-8656-6bfb41c3d67e.png)
