### ISSUE TITLE
Need a dotted form of U+1002

### ISSUE THREAD

**Issue by jcoblentz** [silnrsi/font-padauk#38]
We need a dotted form of u1002 (name: u1002.kham) to complete the set of official dotted forms in the Unicode Standard.

Dot should be on the lower left leg. See u1000.kham for reference. APs should be identical to u1002.

**Comment by devosb** [comment]
![image](https://github.com/silnrsi/font-padauk/assets/12450072/4626ed0a-edc2-4246-92bb-a62eb243a256)
