### ISSUE TITLE
use QIN instead of CSH language tag

### ISSUE THREAD

**Issue by mhosken** [silnrsi/font-padauk#39]
the Asho Chin language 'csh' is mapped to the internal OT language tag of QIN. We should change the OT code accordingly.

Part of the problem with QIN is that it ise OT langtag for the following languages: bgr, biu, cbl, cek, cey, cfm, cka, ckn, clj, clt, cmr, cnb, cnh, cnk, cnw, csh, csj, csv, csy, ctd, cth, czt, dao, flm, gnb, hlt, hmr, hra, lus, mrh, mwq, pck, pkh, pub, puz, ral, rtc, sch, sez, shl, smt, tcp, tcz, vap, weu, yos, zom, zyp. Just a few to check that they all want the same styling!

Of these only csh is written in Myanmar script, so we're probably OK changing the langtag code in the OT font from CSH to QIN. (Nb flm is a dead langtag and not in any registry).

I notice that padauk.fea has a reference to mym2_locl_fea for which there is no lookup (it has been renamed to cv03), and yet the per font .ufo/features.fea does have the lookup. So I'm not sure what is going on there and why the fea compiler doesn't throw a wobbly.

**Comment by mhosken** [comment]
I propose we double map the language as CSH and QIN since harfbuzz maps csh -> CSH and MS maps csh -> QIN.

**Comment by jcoblentz** [comment]
Double mapped CSH and QIN in release 5.001. 
Will continue to research differences in OpenType language tags between harfbuzz and Microsoft's registry - see issue #40.
