### ISSUE TITLE
103C shaping

### ISSUE THREAD

**Issue by Lionslayer** [silnrsi/font-padauk#4]
103C has a long leg crossing other characters, especially when stacked.
https://postimg.org/image/n6creadyr/6be94e71/
ဣန္ဒြေ (composure)
မတ္တြာ (pronunciation form of မတြာ)
စန္ဒြာ (sandra)

**Comment by jcoblentz** [comment]
Yes, we'll need to add some glyphs and contextual substitution rules to fix this. Thank you for the report.

**Comment by mhosken** [comment]
I propose special forms of the following subjoined forms:

1000, 1006, 100C, 1010, 1012, 1013, 1015, 1019, 101E, 103D

**Comment by jcoblentz** [comment]
Also need the .sml versions of the following subjoined forms:
1002, 1005, 1007, 101F
