### ISSUE TITLE
add pwo digits

### ISSUE THREAD

**Issue by mhosken** [silnrsi/font-padauk#41]
Proposal to add pwo digits as variants of shan digits. The language code is KJP. Here are some samples.
![image](https://user-images.githubusercontent.com/5687149/160324101-63d2612d-7e16-41ba-ad03-b59d0f95b634.png)
![image](https://user-images.githubusercontent.com/5687149/160324229-571aae3f-f0cc-43d1-b78d-34bf04fe22db.png)

KP Font 50 style is preferred with the digit 9 coming from the primer (first sample) or KP Font 46

**Comment by devosb** [comment]
@bhirsb drew the digits

![image](https://github.com/silnrsi/font-padauk/assets/12450072/f3d14fb9-74a1-4a63-8726-4cdf397afa31)
