### ISSUE TITLE
change 1037 position for 1070

### ISSUE THREAD

**Issue by mhosken** [silnrsi/font-padauk#42]
For Pwo Karen (kjp) they request the position of 1037 in relation to 1070 to be on the right, in keeping with all the other -ha type characters and their position of 1037.

I'm not sure if any other languages use this character and what they prefer for the position. Given that we have 106F having 1037 on the right, it seems like 1070 was specifically chosen that way. If so, is it only used on the left for a language that already needs language specific styling and we can change the default?

**Comment by devosb** [comment]
> Given that we have 106F having 1037 on the right

This is correct for the Graphite shaping, but not the OpenType shaping.
![image](https://github.com/user-attachments/assets/5c40c205-c184-4170-b891-76446add66ac)

The screenshot is from Firefox, so the OpenType shaping is via HarfBuzz. The dot is also on the left with CoreText OT shaping and the Padauk font.

Given this difference between Graphite and OpenType, and how the other fonts have different positions as shown above (in further testing, the font Myanmar Text on Windows in Word and the default font on iOS for Myanmar have the dot on the right) what should the shaping be?

**Comment by devosb** [comment]
After review, the Padauk OpenType shaping is good, and since Graphite shaping will be removed after the 5.100 release, we don't need to fix the Graphite shaping now.
