### ISSUE TITLE
[Question] How to use alternate glyph?

### ISSUE THREAD

**Issue by hnhtag** [silnrsi/font-padauk#43]
I am creating keyboard layout for Tai Laing (tjl). I want to use uAA6C.alt glyph instead of uAA6C (ꩬ).
How do I use this or other alternate glyphs?

Thanks.

**Comment by jcoblentz** [comment]
Thank you for asking this question. Displaying an alternate glyph is normally done by an app (such as LibreOfffice, Microsoft Word, Adobe InDesign and many web browsers) and not done by a keyboard. It involves setting a feature in the app.
However, you have shown us there is a bug. **A feature to access the uAA6C.alt glyph is missing in the Padauk font. We will fix this by adding a feature for uAA6C.alt as soon as we have resources available to do this.**
In the meantime, you can finish working on the keyboard layout and include a key for U+AA6C. Then when you set the feature in the app (once we have added the feature in Padauk), the app will show uAA6C.alt in place of uAA6C. Also, once we fix this, I can show you how to set the feature in the app. Let me know which apps you normally use.

**Comment by jcoblentz** [comment]
[TODO] Add a Graphite and OpenType feature for accessing uAA6C.alt.

**Comment by hnhtag** [comment]
Thanks for your detailed response. I normally use MS Office, LibreOfffice, Adobe Photoshop, and most popular browsers.

**Comment by jcoblentz** [comment]
Features (cv09 and ss09) have been added to the new release version 5.001 to get access to the U+AA6C variant. The font can be downloaded at https://software.sil.org/padauk/download/. In the download package is a **web folder** where you can study the html and css files on how to access this feature. Here is a screenshot of part of the html:
![image](https://user-images.githubusercontent.com/12460265/172876388-4deb539e-72c8-4f5f-98ef-02139266b903.png)

For **LibreOffice**, select the character, in the menu go to Format, Character, make sure Padauk is the font, then click on the Features button and select the "Tai Laing variant" box as illustrated here:
![LibreOffice features dialog cv09](https://user-images.githubusercontent.com/12460265/172879733-5c0d5120-9e38-492c-a32c-6067377ac171.jpg)

Similarly, for Microsoft **Word** and Adobe **InDesign**, go to the Stylistic Sets dialog and select Stylistic Set 9.

**Comment by hnhtag** [comment]
Thank you for feature release. It works on LibreOffice perfectly. I'll try with other apps.
