### ISSUE TITLE
Facing build error - Text file busy: 'glyphs'

### ISSUE THREAD

**Issue by hnhtag** [silnrsi/font-padauk#44]
Reproduction
---

1. A fresh clone repo
2. Build font with [Building Font Projects note](https://silnrsi.github.io/silfontdev/en-US/Building_Font_Projects.html), and it was finished successfully.
3. Then, type 
`smith distclean`
`smith configure`
`smith build`

I was facing the error below.

![image](https://user-images.githubusercontent.com/24795480/169966844-afc025d0-4e24-4ebc-bc51-a39e5b213e45.png)

The above error reproduction is a sample of showing error on my machine. It frequently occurs on any changes (such as normalizing `./preflight`)

Dev Environment
---

- Windows 10 (i5 4thGen, Ram 8)
- According to the [Setting Up Tools note](https://silnrsi.github.io/silfontdev/en-US/Setting_Up_Tools.html), Tools are installed

> - Vagrant 2.2.19 amd64 
> - VirtualBox 5.2.44 and ext pack

**Comment by bobh0303** [comment]
This is common error if the guest additions are the wrong version, and I've had this trouble. Please check the status of vb guest additions:
```vagrant vbguest --status```

If it is the wrong version, try fixing with:
```vagrant vbguest --do install```

**Comment by hnhtag** [comment]
It has helped me. ကျေးဇူးအများကြီးတင်ပါတယ်။
