### ISSUE TITLE
Missing glyph and not rendered as expected for Tai Laing 

### ISSUE THREAD

**Issue by hnhtag** [silnrsi/font-padauk#45]
I am facing some differences and needs.

1. There is no alternate glyph for uA9E4 and uA9E4 like unicode glyph shape^1 or Noto Sans Myanmar

![image](https://user-images.githubusercontent.com/24795480/172302908-e0b93d36-276a-4ac6-a6dd-1fbd008b870a.png)

3. Not rendered as expected rendering position

![image](https://user-images.githubusercontent.com/24795480/172355244-cff1e882-6025-42b8-a519-81c49f92f04c.png)

Test data: 
[github-issue-attach.pdf](https://github.com/silnrsi/font-padauk/files/8852316/github-issue-attach.pdf)

Footnotes
---
^1 Unicode shapes are from [Myanmar Extended-B](https://unicode.org/charts/PDF/UA9E0.pdf)

**Comment by jcoblentz** [comment]
Thank you for the report of these issues. We will be looking into this.

**Comment by devosb** [comment]
I have started to update the Padauk font. Thank you for mentioning the alternative glyphs.

How should I describe the alternative glyphs as compared to the existing glyphs? Are they older forms, or associated with a language or region, or just a different style? A good description would help in naming the glyphs (I used `.alt` for now) and in any character variant or stylistic set features.

I am curious what application you are using, and how you might expect to access (such as picking the glyphs in InDesign, or through a character variant or stylistic set feature) the alternative glyphs.

**Comment by devosb** [comment]
@bhirsb drew the alternate shapes, there is no cv or ss feature for them yet, but you can see what they look like here
![image](https://github.com/silnrsi/font-padauk/assets/12450072/8fb76696-67fd-465a-8f9a-a15f3f3cb7ca)

**Comment by devosb** [comment]
The shaping issues should be fixed in https://github.com/silnrsi/font-padauk/commit/72fea823f3384649f723ab6ead85e6a7035de8e0. The dot below (1037) will probably be positioned even lower, to be consistent with the location of the dot below after RA and the U and UU vowel signs.

**Comment by devosb** [comment]
Where should the lower dot (1037) be positioned? I tried to match what was in the example you provided, you can see how it looks (in Padauk and other fonts as well). The last row shows where the dot is after ra (101B)
![image](https://github.com/user-attachments/assets/78e0af07-0545-4651-afb0-eaee2ddbf26b)

**Comment by devosb** [comment]
If I change Padauk so that the lower dot after 1083 is more like it is after 101B then result is
![image](https://github.com/user-attachments/assets/fa747770-36a0-4be8-ab9e-9a99527bf93f)

**Comment by mhosken** [comment]
that looks nicer. Good job

**Comment by devosb** [comment]
You can now access the alternate forms of U+A9E4 and U+A9E8 with the `cv10` and/or `ss10` features, depending on your application.

Just curious, are you a Tai Laing speaker?

**Comment by hnhtag** [comment]
Thanks for the update. I am Burmese speaker.
I have researched and did consulting about font to use in the Tai Laing ethnic group.
