### ISSUE TITLE
AnontaMon kicked up a few bugs??

### ISSUE THREAD

**Issue by Mercury13** [silnrsi/font-padauk#46]
I don’t know Myanmar, I’m just the author of Unicodia, encyclopedia of characters, so I’ll send you to original issue
https://github.com/googlefonts/noto-fonts/issues/1926

Here’s my quick test with MS Myanmar Text and your Padauk Book. As you see, for some reason the last line is tolerable misrender in M$, and very evil (technical signs visible) in yours.

![image](https://user-images.githubusercontent.com/10164882/172366713-c4ded7c3-0cde-499b-990d-c9ec2a4f49a1.png)

The last line is &#x1007;&#x1039;&#x1009; &#x1012;&#x1039;&#x1009; = 1007 1039 1009 space 1012 1039 1009

**Comment by jcoblentz** [comment]
Thank you for the report of these issues. We will be looking into this.

**Comment by devosb** [comment]
With the changes in https://github.com/silnrsi/font-padauk/commit/85c47e5170ac18261ac372857979415360537132 this issue should be resolved. @Anontamon, please review this issue and anything in the linked Noto issue.
