### ISSUE TITLE
Dot positions for left shifted (ksw)

### ISSUE THREAD

**Issue by mhosken** [silnrsi/font-padauk#50]
The dot when shifted left needs to be much closer to the lower diacritic it is left of, including moving upwards if that helps. The issue is that if the dot is too far left, it can look like it is part of the previous character.

**Comment by devosb** [comment]
The character sequence that promoted this issue is
```
U+101B MYANMAR LETTER RA
U+103D MYANMAR CONSONANT SIGN MEDIAL WA
U+1037 MYANMAR SIGN DOT BELOW
```
Does the dot need to be shifted in other cases? For example,
```
U+1015 MYANMAR LETTER PA
U+103D MYANMAR CONSONANT SIGN MEDIAL WA
U+1037 MYANMAR SIGN DOT BELOW
```
exists in the test data, and looks like it would have the same issue. More generally, does this issue apply to any character sequence where the dot is to the left of a medial (such as medial KA)?

**Comment by devosb** [comment]
With U+103D with a PA (narrow), GHA (wide), and RA base
![image](https://github.com/user-attachments/assets/8fad700b-a282-4332-b18e-49840522ef53)
and with _Tear drop style washwe_
![image](https://github.com/user-attachments/assets/425c65e5-c40c-4356-86ff-59dca8aa1b35)
With the same bases, but with medial KA (wide)
![image](https://github.com/user-attachments/assets/8e00d783-0b63-4eba-8bc0-dbfec78da793)
With the same bases, but with medial KHA (narrow)
![image](https://github.com/user-attachments/assets/1d86312b-ee64-4cc1-92cf-e722ea705284)
As expected, wide bases have less issues than narrow bases, unless the medial below is also wide. All the examples have CHA at the start, so you can see how much the dot moves under that preceding character.

**Comment by mhosken** [comment]
For Sgaw Karen, which is where the dot is put on the left. The only sequence of interest involves the wa shwe, your 1st and 2nd sets of examples. Sgaw Karen doesn't do syllable chaining and so the other examples don't apply. Things look good, although it might be worth moving the dot up and to the right slightly when under the ra (101B, last of the 3) to try to tuck the dot closer into a more cluster feel rather than a sequence feel. I know both styles of the wa shwe are used so we need to think about them both. Note that this move only really works with a narrow base. Under a wide base there isn't a gap to slot into and the dot doesn't need to move either because it has space to live under the wide base.
I wouldn't raise any of the dot above the top of the wa shwe. Perhaps align it with the top of the wa shwe in each case and then move it as close right as makes sense such that it's horizontal gap remains the same as it is now (so for the round wa shwe move North by NorthEast, and for the teardrop move it NorthEast)

**Comment by devosb** [comment]
The location of dot has been moved as suggested. Note how close the dot is in the 3rd party fonts, and how close it is in Padauk (Graphite) with a RA base. I am not sure why the dot is so close with Graphite and RA (and not the other bases).
![image](https://github.com/user-attachments/assets/bb4e2773-0b76-4fec-ba63-ba7e868e2f75)

**Comment by devosb** [comment]
FYI, The screen shot was made with un-commited changes.
