### ISSUE TITLE
Myanmar extended C

### ISSUE THREAD

**Issue by Mercury13** [silnrsi/font-padauk#51]
Add 20 digits of Myanmar minorities
![изображение](https://github.com/silnrsi/font-padauk/assets/10164882/637c3e89-ad83-4157-afad-239a2825853b)

**Comment by devosb** [comment]
Thanks for showing part of the [proposal](https://www.unicode.org/L2/L2022/22046-myanmar-numerals.pdf) from @ohbendy. The Pa'O digits were added in https://github.com/silnrsi/font-padauk/commit/288194d4df7f2d8053e237783d8993ab4172190c and look like
![image](https://github.com/silnrsi/font-padauk/assets/12450072/6319b96f-601a-46c8-b031-09f04009a6e6)

The Pwo digits were added in https://github.com/silnrsi/font-padauk/commit/ca713be6bb3da1c3be498098dbfd50b6be19c570, you can see what they look like in [another comment](https://github.com/silnrsi/font-padauk/issues/41#issuecomment-2159305871).

**Comment by Mercury13** [comment]
Thank you.
