### ISSUE TITLE
Latin glyphs should be base glyphs, not mark

### ISSUE THREAD

**Issue by brawer** [silnrsi/font-padauk#7]
The GDEF table in Padauk gives class 3 (mark) to lots of Latin glyphs that should be normal base glyphs, not marks. See https://github.com/behdad/harfbuzz/issues/305. (Filing here because it’s a Padauk issue).

**Comment by jcoblentz** [comment]
RE: Padauk issue #1 
This bug is now fixed in the released version 3.001 available on the official product page for Padauk http://software.sil.org/padauk/download/

**Comment by jcoblentz** [comment]
Closing #7. Referencing  behdad/harfbuzz#305. (Bug has been fixed).
