### ISSUE TITLE
Asho Chin needs

### ISSUE THREAD

**Issue by mhosken** [silnrsi/font-padauk#8]
Asho Chin: csh

- sequences to support: U+103E U+1060, U+103D U+1060 probably needing their own ligatures.

- The preferred form of U+103E is slanted with a 90 degree foot.

- Also they like U+106D to be closed at the top.

- They also have tone marks after U+1038. Particularly U+1069, U+106A, U+106C. These currently fall foul of the sequence checker. Apparently this is a bug in UTN#11, and the tone marks should occur after U+1038 in all cases and not before.

- U+1061 U+103D should render correctly but doesn't.

See enclosed PDF
[Asho_Unicode_codes_and_combinations.pdf](https://github.com/silnrsi/font-padauk/files/688645/Asho_Unicode_codes_and_combinations.pdf)

**Comment by ojgamache** [comment]
Just to clarify; the preferred form of U+ 103E is vertical when alone; when combined with other descenders, I'm seeing some vertical, some slanted with 90 degree foot, some slanted with flat foot - I'm not sure if there is consensus on a preferred form.
![consonant combinations](https://cloud.githubusercontent.com/assets/25482252/22509295/dd19c94e-e8bb-11e6-9a3d-b654a5f0852e.jpg)

![pg 2](https://cloud.githubusercontent.com/assets/25482252/22509024/b5ab519e-e8ba-11e6-8a13-45d894819ffe.jpg)

**Comment by jvgaultney** [comment]
Need a clear spec - a list of all the new glyphs that are needed, as in:

glyphname - encoding - description
uni106d.csh - (none) - as uni106d but closed at top

**Comment by mhosken** [comment]
New glyphs of which none are encoded:

u106D.csh - as u106D but closed at top as per column 3 in Lesson 1 in picture above
u103E_u106D.csh - ligature diacritic with APs as per u103E and design as per chart above (bottom row first cell). Note u103E.slanth
u103D_u106D.csh - ligature diacritic with APs as per u103D and design as per chart above (6th row first cell)

**Comment by mhosken** [comment]
Design shape questions. Which of these do you prefer and why and how would you modify it to make it even better?
[106D.csh feedback.pdf](https://github.com/silnrsi/font-padauk/files/2500789/106D.csh.feedback.pdf)

**Comment by mhosken** [comment]
Problem is that the shaper is inserting a dotted circle between 103E and 1060. Also need to allows tone marks after 1038. Need to follow up with harfbuzz.

**Comment by jcoblentz** [comment]
On U+1061 move attachment point BS left so U+103D positions in the proper location. Check positioning of other marks that have BS.

**Comment by mhosken** [comment]
The shaping for all this works in Graphite, but not in OT mym2 due to a bug in mym2.
